In [1]:
import numpy as np
import ex1

In [2]:
z1 = 1.0
z2 = 4.0
z3 = 7.0
z4 = 10.0

In [3]:
zA = 7.3
zB = 10.1
zC = 3.8
zD = 1.2

In [4]:
# Prior (b)
p_x1 = 1/6
p_x2 = 1/3
p_x3 = 1/3
p_x4 = 1/6

### Measurement A

In [5]:
mean = (z1 - 0.1)
sigma = (0.25 + 0.05*zA)
p_x1_zA = ex1.gaussian_distribution(mean, sigma, zA) * p_x1

In [6]:
mean = (z2 - 0.1)
sigma = (0.25 + 0.05*zA)
p_x2_zA = ex1.gaussian_distribution(mean, sigma, zA) * p_x2

In [7]:
mean = (z3 - 0.1)
sigma = (0.25 + 0.05*zA)
p_x3_zA = ex1.gaussian_distribution(mean, sigma, zA) * p_x3

In [8]:
mean = (z4 - 0.1)
sigma = (0.25 + 0.05*zA)
p_x4_zA = ex1.gaussian_distribution(mean, sigma, zA) * p_x4

In [9]:
# Normalization
p_x_zA = [p_x1_zA, p_x2_zA, p_x3_zA, p_x4_zA]
p_x_zA_norm = ex1.softmax(p_x_zA)

In [10]:
p_x_zA

[3.2949760710910247e-25,
 4.989591369871983e-08,
 0.17500650733785517,
 1.4217391347576257e-05]

In [11]:
p_x_zA_norm

array([0.23859127, 0.23859128, 0.28422279, 0.23859466])

### Measurement B

In [12]:
mean = (z1 - 0.1)
sigma = (0.25 + 0.05*zB)
p_x1_zB = ex1.gaussian_distribution(mean, sigma, zB) * p_x1

In [13]:
mean = (z2 - 0.1)
sigma = (0.25 + 0.05*zB)
p_x2_zB = ex1.gaussian_distribution(mean, sigma, zB) * p_x2

In [14]:
mean = (z3 - 0.1)
sigma = (0.25 + 0.05*zB)
p_x3_zB = ex1.gaussian_distribution(mean, sigma, zB) * p_x3

In [15]:
mean = (z4 - 0.1)
sigma = (0.25 + 0.05*zB)
p_x4_zB = ex1.gaussian_distribution(mean, sigma, zB) * p_x4

In [16]:
# Normalization
p_x_zB = [p_x1_zB, p_x2_zB, p_x3_zB, p_x4_zB]
p_x_zB_norm = ex1.softmax(p_x_zB)

In [17]:
p_x_zB

[5.032288736265916e-34,
 4.0029388421063697e-16,
 2.213002039295563e-05,
 0.08503038182417262]

In [18]:
p_x_zB_norm

array([0.24457219, 0.24457219, 0.2445776 , 0.26627801])

### Measurement C

In [19]:
mean = (z1 - 0.1)
sigma = (0.25 + 0.05*zC)
p_x1_zC = ex1.gaussian_distribution(mean, sigma, zC) * p_x1

In [20]:
mean = (z2 - 0.1)
sigma = (0.25 + 0.05*zC)
p_x2_zC = ex1.gaussian_distribution(mean, sigma, zC) * p_x2

In [21]:
mean = (z3 - 0.1)
sigma = (0.25 + 0.05*zC)
p_x3_zC = ex1.gaussian_distribution(mean, sigma, zC) * p_x3

In [22]:
mean = (z4 - 0.1)
sigma = (0.25 + 0.05*zC)
p_x4_zC = ex1.gaussian_distribution(mean, sigma, zC) * p_x4

In [23]:
# Normalization
p_x_zC = [p_x1_zC, p_x2_zC, p_x3_zC, p_x4_zC]
p_x_zC_norm = ex1.softmax(p_x_zC)

In [24]:
p_x_zC

[5.5771464140671095e-11,
 0.2945234312951117,
 5.029074494639433e-12,
 2.7766215997891607e-43]

In [25]:
p_x_zC_norm

array([0.23028282, 0.30915155, 0.23028282, 0.23028282])

### Measurement D

In [26]:
mean = (z1 - 0.1)
sigma = (0.25 + 0.05*zD)
p_x1_zD = ex1.gaussian_distribution(mean, sigma, zD) * p_x1

In [27]:
mean = (z2 - 0.1)
sigma = (0.25 + 0.05*zD)
p_x2_zD = ex1.gaussian_distribution(mean, sigma, zD) * p_x2

In [28]:
mean = (z3 - 0.1)
sigma = (0.25 + 0.05*zD)
p_x3_zD = ex1.gaussian_distribution(mean, sigma, zD) * p_x3

In [29]:
mean = (z4 - 0.1)
sigma = (0.25 + 0.05*zD)
p_x4_zD = ex1.gaussian_distribution(mean, sigma, zD) * p_x4

In [30]:
# Normalization
p_x_zD = [p_x1_zD, p_x2_zD, p_x3_zD, p_x4_zD]
p_x_zD_norm = ex1.softmax(p_x_zD)

In [31]:
p_x_zD

[0.13428682953274373,
 1.445331006998814e-17,
 1.6524601036229115e-74,
 2.0068938844382095e-172]

In [32]:
p_x_zD_norm

array([0.276013, 0.241329, 0.241329, 0.241329])